# Generated by Django 3.0.2 on 2020-01-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200118_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='unique_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='unique_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
