# Generated by Django 3.0.2 on 2020-01-16 23:44

from django.db import migrations, models
import django.db.models.deletion
import hospital.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('quantity', models.IntegerField()),
                ('consumption', models.CharField(max_length=10)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=300)),
                ('bio', models.TextField()),
                ('cover_pic', models.ImageField(blank=True, null=True, upload_to=hospital.models.hospital_profile_pic_path)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(max_length=10)),
                ('fax_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.City')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.State'),
        ),
    ]
