# Generated by Django 3.0.2 on 2020-01-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
