# Generated by Django 3.0.2 on 2020-01-17 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('hospital', '0005_auto_20200117_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Doctor'),
        ),
    ]
