# Generated by Django 3.0.2 on 2020-01-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_auto_20200117_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
