# Generated by Django 3.0.2 on 2020-01-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_appointment_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
