# Generated by Django 3.0.2 on 2020-01-18 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0010_appointment_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='password',
        ),
        migrations.AddField(
            model_name='hospital',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
