# Generated by Django 3.0.2 on 2020-01-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_auto_20200118_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
