# Generated by Django 3.0.2 on 2020-01-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_auto_20200118_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='name',
            field=models.CharField(default='Something', max_length=50),
        ),
    ]
