# Generated by Django 3.0.2 on 2020-01-18 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200118_0834'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0017_auto_20200118_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Patient'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.State'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.City'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
