# Generated by Django 3.0.2 on 2020-01-18 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200118_1055'),
        ('hospital', '0018_auto_20200118_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_appointments', to='user.Doctor'),
        ),
    ]
